## Tensor概述
对于Tensor的操作很多，从接口角度来讲，可以分为两类
- torch.function，如torch.sum、torch.add等
- tensor.function，如tensor.view、tensor.add等

其中，关于Tensor很多操作都是等价的，如torch.add(x, y)和x.add(y)等价。

从修改方式的角度来看，可以分为两类：
- 不修改自身数据，如x.add(y)，x的数据不变，返回一个新的Tensor。
- 修改自身数据，如x.add_(y)（运算符带下划线），运算结果存在x中。

In [1]:
import torch

In [2]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
z = x.add(y)
print(x, y, z)
x.add_(z)
print(x)

tensor([1, 2]) tensor([3, 4]) tensor([4, 6])
tensor([5, 8])


## 创建Tensor

In [4]:
# 依据list数据生成Tensor
print(torch.Tensor([1,2,3,4,5,6]))
# 指定形状生成Tensor
print(torch.Tensor(2,3))
# 直接给定Tensor的形状
t = torch.Tensor([[1,2,3],[4,5,6]])
# 查看Tensor形状
print(t.size())
# shape与size()等价方式
print(t.shape)
# 依据已有形状创建Tensor
print(torch.Tensor(t.size()))

tensor([1., 2., 3., 4., 5., 6.])
tensor([[1.7502e+05, 7.6091e-43, 8.4078e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])
torch.Size([2, 3])
torch.Size([2, 3])
tensor([[0.0000e+00, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 1.8208e+03, 7.6091e-43]])


**torch.Tensor**和**torch.tensor**的区别
- torch.Tensor是torch.empty和torch.tensor之间的一种混合，传入数据时，torch.Tensor使用全局默认dtype(FloatTensor)，而torch.tensor是从数据中推断数据类型。
- torch.tensor(1)返回一个固定值1，而torch.Tensor(1)返回的是一大小为1的张量，它是随机初始化的值。

In [6]:
t1 = torch.Tensor(1)
t2 = torch.tensor(1)
print(t1, t1.type(), t2, t2.type())

tensor([9.8265e-39]) torch.FloatTensor tensor(1) torch.LongTensor


自动生成Tensor的一些例子

In [7]:
# 生成一个单位矩阵
print(torch.eye(2,2))
# 自动生成全是0的矩阵
print(torch.zeros(2,3))
# 
print(torch.linspace(1, 10, 4))
# 生成满足均匀分布随机数
print(torch.rand(2,3))
# 生成满足标准分布随机数
print(torch.randn(2,3))
# 返回所给数据形状相同，值全为0的张量
print(torch.zeros_like(torch.rand(2,3)))

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([ 1.,  4.,  7., 10.])
tensor([[0.0394, 0.6398, 0.0280],
        [0.6528, 0.4758, 0.0115]])
tensor([[-1.1267,  1.8329, -1.5849],
        [ 1.3063, -0.5739,  0.1458]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 修改Tensor形状

In [8]:
x = torch.randn(2, 3)
print(x.size())
print(x.dim())
# 修改x的形状
print(x.view(3,2))
y = x.view(-1)
print(y.shape, x.shape)
z = torch.unsqueeze(y, 0)  # 对y添加一个维度
print(z, z.size())
print(z.numel())  #计算z中元素的个数

torch.Size([2, 3])
2
tensor([[ 0.3625,  0.0661],
        [-0.0812,  1.6973],
        [-0.0054, -1.4974]])
torch.Size([6]) torch.Size([2, 3])
tensor([[ 0.3625,  0.0661, -0.0812,  1.6973, -0.0054, -1.4974]]) torch.Size([1, 6])
6


## 索引操作

In [10]:
# 设置一个随机种子
torch.manual_seed(2020)
# 生成一个2x3的矩阵
x = torch.randn(2, 3)
print(x)
print('The First Row', x[0,:])
print('The last col', x[:, -1])
mask = x > 0
print('生成是否大于0的Byter张量', mask)
# 获取其值
print(torch.masked_select(x, mask))
# 获取非0下标，即行列坐标
print(torch.nonzero(mask))  # False:0, True:1
index = torch.LongTensor([[0, 1, 1]]) 
print('index', index)
# out[i][j][k] = input[index[i][j][k]][j][k]  # dim=0
# out[i][j][k] = input[i][index[i][j][k]][k]  # dim=1
# out[i][j][k] = input[i][j][index[i][j][k]]  # dim=2

print(torch.gather(x, 0, index)) # torch.gather(input, dim, index, out=None) → Tensor
index = torch.LongTensor([[0,1,1], [1,1,1]])
print('index', index)
a = torch.gather(x, 1, index)
print('a', a)
z = torch.zeros(2,3)
print(z)
z.scatter_(1, index, a)
print(z)

tensor([[ 1.2372, -0.9604,  1.5415],
        [-0.4079,  0.8806,  0.0529]])
The First Row tensor([ 1.2372, -0.9604,  1.5415])
The last col tensor([1.5415, 0.0529])
生成是否大于0的Byter张量 tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([1.2372, 1.5415, 0.8806, 0.0529])
tensor([[0, 0],
        [0, 2],
        [1, 1],
        [1, 2]])
index tensor([[0, 1, 1]])
tensor([[1.2372, 0.8806, 0.0529]])
index tensor([[0, 1, 1],
        [1, 1, 1]])
a tensor([[ 1.2372, -0.9604, -0.9604],
        [ 0.8806,  0.8806,  0.8806]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 1.2372, -0.9604,  0.0000],
        [ 0.0000,  0.8806,  0.0000]])


## 广播机制